name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build-type: Release
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"
          path: "FnordLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@v7
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
<<<<<<< HEAD:.github/workflows/trigger_release.yml
          mv ${{ github.workspace }}/FnordLauncher-source FnordLauncher-${{ env.VERSION }}
          mv FnordLauncher-Linux-Qt6-Portable*/FnordLauncher-portable.tar.gz FnordLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv FnordLauncher-Linux-Qt5-Portable*/FnordLauncher-portable.tar.gz FnordLauncher-Linux-Qt5-Portable-${{ env.VERSION }}.tar.gz
          mv FnordLauncher-*.AppImage/FnordLauncher-*.AppImage FnordLauncher-Linux-x86_64.AppImage
          mv FnordLauncher-*.AppImage.zsync/FnordLauncher-*.AppImage.zsync FnordLauncher-Linux-x86_64.AppImage.zsync
          mv FnordLauncher-macOS-Legacy*/FnordLauncher.zip FnordLauncher-macOS-Legacy-${{ env.VERSION }}.zip
          mv FnordLauncher-macOS*/FnordLauncher.zip FnordLauncher-macOS-${{ env.VERSION }}.zip
=======
          mv ${{ github.workspace }}/FjordLauncher-source FjordLauncher-${{ env.VERSION }}
          mv FjordLauncher-Linux-Qt6-Portable*/FjordLauncher-portable.tar.gz FjordLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv FjordLauncher-Linux-aarch64-Qt6-Portable*/FjordLauncher-portable.tar.gz FjordLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv FjordLauncher-*.AppImage/FjordLauncher-*-x86_64.AppImage FjordLauncher-Linux-x86_64.AppImage
          mv FjordLauncher-*.AppImage.zsync/FjordLauncher-*-x86_64.AppImage.zsync FjordLauncher-Linux-x86_64.AppImage.zsync
          mv FjordLauncher-*.AppImage/FjordLauncher-*-aarch64.AppImage FjordLauncher-Linux-aarch64.AppImage
          mv FjordLauncher-*.AppImage.zsync/FjordLauncher-*-aarch64.AppImage.zsync FjordLauncher-Linux-aarch64.AppImage.zsync
          mv FjordLauncher-macOS*/FjordLauncher.zip FjordLauncher-macOS-${{ env.VERSION }}.zip
>>>>>>> upstream/HEAD:.github/workflows/release.yml

          tar --exclude='.git' -czf FnordLauncher-${{ env.VERSION }}.tar.gz FnordLauncher-${{ env.VERSION }}

          for d in FnordLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            ARM64="$(echo -n ${d} | grep -o arm64 || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="FnordLauncher-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${ARM64}" || NAME="${NAME}-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv FnordLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in FnordLauncher-Windows-MinGW-w64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="FnordLauncher-Windows-MinGW-w64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv FnordLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in FjordLauncher-Windows-MinGW-arm64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="FjordLauncher-Windows-MinGW-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv FjordLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Fnord Launcher ${{ env.VERSION }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
<<<<<<< HEAD:.github/workflows/trigger_release.yml
            FnordLauncher-Linux-Qt5-Portable-${{ env.VERSION }}.tar.gz
            FnordLauncher-Linux-x86_64.AppImage
            FnordLauncher-Linux-x86_64.AppImage.zsync
            FnordLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            FnordLauncher-Windows-MinGW-w64-${{ env.VERSION }}.zip
            FnordLauncher-Windows-MinGW-w64-Portable-${{ env.VERSION }}.zip
            FnordLauncher-Windows-MinGW-w64-Setup-${{ env.VERSION }}.exe
            FnordLauncher-Windows-MSVC-arm64-${{ env.VERSION }}.zip
            FnordLauncher-Windows-MSVC-arm64-Portable-${{ env.VERSION }}.zip
            FnordLauncher-Windows-MSVC-arm64-Setup-${{ env.VERSION }}.exe
            FnordLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            FnordLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            FnordLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            FnordLauncher-macOS-${{ env.VERSION }}.zip
            FnordLauncher-macOS-Legacy-${{ env.VERSION }}.zip
            FnordLauncher-${{ env.VERSION }}.tar.gz
=======
            FjordLauncher-Linux-x86_64.AppImage
            FjordLauncher-Linux-x86_64.AppImage.zsync
            FjordLauncher-Linux-aarch64.AppImage
            FjordLauncher-Linux-aarch64.AppImage.zsync
            FjordLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            FjordLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
            FjordLauncher-Windows-MinGW-w64-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MinGW-w64-Portable-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MinGW-w64-Setup-${{ env.VERSION }}.exe
            FjordLauncher-Windows-MinGW-arm64-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MinGW-arm64-Portable-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MinGW-arm64-Setup-${{ env.VERSION }}.exe
            FjordLauncher-Windows-MSVC-arm64-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MSVC-arm64-Portable-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MSVC-arm64-Setup-${{ env.VERSION }}.exe
            FjordLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            FjordLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            FjordLauncher-macOS-${{ env.VERSION }}.zip
            FjordLauncher-${{ env.VERSION }}.tar.gz
>>>>>>> upstream/HEAD:.github/workflows/release.yml
